### ISSUE TITLE
please do work from a personal fork

### ISSUE THREAD

**Issue by beckermr** [conda-forge/iterativewgcna-feedstock#11] opened 2020-10-26 18:36 UTC
@thompsonsed I think you might be pushing directly to a branch in this feedstock. This causes an upload and release of a package for each commit you make. If this is the case, please work from a fork of the repo and PR as stated in our documentation. Cheers and thank you for being a great maintainer and working on this package!

**Comment by isuruf** [comment] 2020-10-26 19:36
Hi, @thompsonsed, I've enabled branch protection so that commits are not accidentally pushed to this repo. Let me know and I can remove it.
As for the background, the package here seems to be almost 1GB and each build pushes a number of builds which results in our staging server getting full and all the other packages in conda-forge started failing to upload. We'll try and fix this so that we can accomodate `iterativewgcna`.

Btw, may I ask why this package is vendoring a lot of R libraries when they are available as conda packages? This would reduce the size of the package by a lot and would be in line with our policy of not vendoring other packages into a package.

**Comment by scopatz** [comment] 2020-10-27 17:37
There seems to be one specific artifact that is hanging whenever I mirror: `iterativewgcna-1.1.6-py37r40h43df1e8_10.tar.bz2`

**Comment by chrisburr** [comment] 2020-10-27 17:54
My mirror managed to synchronise it and `wget` seems to work for getting a file with the correct hash:
```
$ wget https://conda-static.anaconda.org/conda-forge/linux-64/iterativewgcna-1.1.6-py37r40h43df1e8_10.tar.bz2
$ openssl md5 iterativewgcna-1.1.6-py37r40h43df1e8_10.tar.bz2
MD5(iterativewgcna-1.1.6-py37r40h43df1e8_10.tar.bz2)= ee3a4cac6f1cdcf226a6c1855c95a634
$ curl -L https://conda-web.anaconda.org/conda-forge/linux-64/repodata.json | jq '.packages."iterativewgcna-1.1.6-py37r40h43df1e8_10.tar.bz2".md5'
"ee3a4cac6f1cdcf226a6c1855c95a634"
```

**Comment by thompsonsed** [comment] 2020-10-28 08:28
Hi, thanks all for the advice. I was actually trying to fix the build problems that I could only reproduce through the CI. Is there a better approach for testing cross-platform builds? Apologies for overloading your staging server! 

I'll have a look in to why the package is vendoring R libraries. It's probably my ignorance and not properly knowing how to fetch R packages - it's been some time since I've tried to update this package (I'm not the original author). I'll try and work on a fix for this. 

Apologies again!

**Comment by chrisburr** [comment] 2020-10-28 09:10
> I was actually trying to fix the build problems that I could only reproduce through the CI. Is there a better approach for testing cross-platform builds? Apologies for overloading your staging server!

It's perfectly fine to use the CI for testing issues that only show up there, the only issue was that you were pushing to the `regro-cf-autotick-bot-rebuild-gcc930-0-1_h319281` branch on `conda-forge/iterativewgcna-feedstock` instead the `rebuild-gcc930-0-1_h319281` of the bot's fork (`regro-cf-autotick-bot/iterativewgcna-feedstock`). This, in combination with the bumping build number, means every build was being uploaded instead of only being tested. Normally the build number only needs to be bumped once per PR (assuming the version hasn't changed).

**Comment by thompsonsed** [comment] 2020-10-28 09:12
I see, my apologies. I definitely got the wrong end of the stick on that process, thanks for correcting me.

**Comment by beckermr** [comment] 2020-10-28 11:42
Thanks for working with us @thompsonsed!

**Closed as completed** 2020-10-30 18:27 UTC
